/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb1",
        "surface-container-low": "#fff1ec",
        "surface-container-lowest": "#ffffff",
        "surface": "#fff8f6",
        "surface-container-high": "#ffe2d7",
        "secondary-container": "#ff8b67",
        "on-secondary-container": "#752407",
        "on-surface-variant": "#44474d",
        "on-secondary": "#ffffff",
        "outline-variant": "#c5c6ce",
        "surface-bright": "#fff8f6",
        "on-tertiary-container": "#a97d37",
        "on-tertiary": "#ffffff",
        "surface-dim": "#f5d3c5",
        "outline": "#75777e",
        "on-primary": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "inverse-on-surface": "#ffede6",
        "surface-container": "#ffe9e1",
        "error": "#ba1a1a",
        "inverse-primary": "#b8c7e5",
        "on-tertiary-fixed-variant": "#614000",
        "inverse-surface": "#402c22",
        "surface-tint": "#515f79",
        "on-error-container": "#93000a",
        "secondary": "#9e4223",
        "on-tertiary-fixed": "#291800",
        "tertiary-fixed-dim": "#f2be71",
        "background": "#fff8f6",
        "on-primary-fixed-variant": "#394760",
        "on-surface": "#29170f",
        "surface-variant": "#fedbcd",
        "secondary-fixed-dim": "#ffb59e",
        "on-secondary-fixed": "#3a0b00",
        "surface-container-highest": "#fedbcd",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0c1c33",
        "tertiary-container": "#2b1a00",
        "on-secondary-fixed-variant": "#7f2b0e",
        "on-background": "#29170f",
        "tertiary": "#060200",
        "secondary-fixed": "#ffdbd0",
        "primary-container": "#0e1d34",
        "primary-fixed-dim": "#b8c7e5",
        "primary": "#00030b",
        "error-container": "#ffdad6",
        "on-primary-container": "#7785a1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "space-lg": "1.5rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"]
      }
    }
  },
  plugins: []
};
